version: 2
updates:
  - package-ecosystem: npm
    # Files stored in repository root
    directory: '/'
    schedule:
      interval: 'daily'
    allow:
      - dependency-name: '@mageswap/token-lists'
      - dependency-name: '@mageswap/default-token-list'
      - dependency-name: '@mageswap/redux-multicall'
    reviewers:
      - 'Uniswap/dependabot-reviewers'
